Eduhome/Eduhome/Models/Teacher.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Eduhome.Models
{
    public class Teacher
    {
        public int Id { get; set; }
        public string Image { get; set; }
        [NotMapped]
        public IFormFile Photo { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public TeacherDetails TeacherDetails { get; set; }

    }
}

Eduhome/Eduhome/Areas/Admin/Controllers/TeacherController.cs
using Eduhome.DAL;
using Eduhome.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eduhome.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TeacherController : Controller
    {
        private readonly AppDbContext _context;
        public TeacherController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            List<Teacher> teachers = _context.Teacher.Include(x => x.TeacherDetails).ToList();
            return View(teachers);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Teacher teacher)
        {
            if (!ModelState.IsValid) return View();
            bool isExist = _context.Teacher.Any(c => c.Name.ToLower().Trim() == teacher.Name.ToLower().Trim());
            if (isExist)
            {
                ModelState.AddModelError("Title", "The person already exists!");
                return View();
            }
            await _context.AddRangeAsync(teacher, teacher.TeacherDetails);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Detail(int? id)
        {

            if (id == null) return NotFound();
            Teacher teacher = await _context.Teacher.FirstOrDefaultAsync(c => c.Id == id);
            if (teacher == null) return NotFound();
            return View(teacher);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null) return NotFound();
            Teacher teacher = await _context.Teacher.FirstOrDefaultAsync(c => c.Id == id);
            if (teacher == null) return NotFound();
            return View(teacher);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeletePost(int? id)
        {
            if (id == null) return NotFound();
            Teacher teacher = await _context.Teacher.FirstOrDefaultAsync(c => c.Id == id);
            if (teacher == null) return NotFound();
            _context.Teacher.Remove(teacher);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int? id)
        {

            if (id == null) return NotFound();
            Teacher teacher = await _context.Teacher.FirstOrDefaultAsync(c => c.Id == id);
            if (teacher == null) return NotFound();
            return View(teacher);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, Teacher teacher)
        {
            if (id == null) return NotFound();
            if (teacher == null) return NotFound();
            Teacher teacherView = await _context.Teacher.FirstOrDefaultAsync(c => c.Id == id);
            if (!ModelState.IsValid)
            {
                return View(teacherView);
            }
            Caption captionDb = await _context.CourseCaptions.FirstOrDefaultAsync(c => c.Title.ToLower().Trim() == teacher.Name.ToLower().Trim());
            if (captionDb != null && captionDb.Id != id)
            {
                ModelState.AddModelError("Course Name", "This Course already exists!");
                return View(teacherView);
            }
            teacherView.Name = teacher.Name;
            teacherView.Position = teacher.Position;
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Eduhome/Eduhome/Controllers/TeacherController.cs
using Eduhome.DAL;
using Eduhome.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eduhome.Controllers
{
    public class TeacherController : Controller
    {
        private readonly AppDbContext _db;
        public TeacherController(AppDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            List<Teacher> teachers = await _db.Teacher.ToListAsync();

            return View(teachers);
        }
        public IActionResult Details(int id)
        {

            TeacherDetails detail = _db.TeacherDetails.Include(det => det.Teacher)
                .FirstOrDefault(det => det.TeacherId == id);


            return View(detail);
        }
        public async Task<IActionResult> Search(string search)
        {
            List<Teacher> teachers = await _db.Teacher.Where(c => c.Name.ToLower().Trim().Contains(search.ToLower().Trim())).ToListAsync();

            return View(teachers);
        }
    }
}

Eduhome/Eduhome/Views/Teacher/Details.cshtml
@{
    ViewData["Title"] = "Details";
    TeacherDetails detail = Model;
}

<!-- Banner Area Start -->
<div class="banner-area-wrapper">
    <div class="banner-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="banner-content-wrapper">
                        <div class="banner-content">
                            <h2>teachers / details</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Area End -->
<!-- Teacher Start -->
<div class="teacher-details-area pt-150 pb-60">
    <div class="container">
        <div class="row">
            <div class="col-md-5 col-sm-5 col-xs-12">
                <div class="teacher-details-img">
                    <img src="~/front/img/teacher/@detail.Teacher.Image" alt="teacher">
                </div>
            </div>
            <div class="col-md-7 col-sm-7 col-xs-12">
                <div class="teacher-details-content ml-50">
                    <h2>@detail.Teacher.Name</h2>
                    <h5>@detail.Teacher.Position</h5>
                    <h4>about me</h4>
                    <p>@detail.AboutMe</p>
                    <ul>
                        <li><span>degree: </span>@detail.Degree</li>
                        <li><span>experience: </span>@detail.Experience</li>
                        <li><span>hobbies: </span>@detail.Hobbies</li>
                        <li><span>faculty: </span>@detail.Faculty</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-4">
                <div class="teacher-contact">
                    <h4>contact information</h4>
                    <p><span>mail me : </span>@detail.MailMe</p>
                    <p><span>make a call : </span>@detail.CallMe</p>
                    <p><span>skype : </span>@detail.Skype</p>
                    <ul>
                        <li><a href="https://www.facebook.com/devitems/?ref=bookmarks"><i class="zmdi zmdi-facebook"></i></a></li>
                        <li><a href="https://www.pinterest.com/devitemsllc/"><i class="zmdi zmdi-pinterest"></i></a></li>
                        <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                        <li><a href="https://twitter.com/devitemsllc"><i class="zmdi zmdi-twitter"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-9 col-sm-8">
                <div class="skill-area">
                    <h4>skills</h4>
                </div>
                <div class="skill-wrapper">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="skill-bar-item">
                                <span>language</span>
                                <div class="progress">
                                    <div data-wow-delay="1.2s" data-wow-duration="1.5s" style="width: 85%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-progress="50%" class="progress-bar wow fadeInLeft">
                                        <span class="text-top">@detail.Language%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="skill-bar-item">
                                <span>team leader</span>
                                <div class="progress">
                                    <div data-wow-delay="1.2s" data-wow-duration="1.5s" style="width: 90%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-progress="50%" class="progress-bar wow fadeInLeft">
                                        <span class="text-top">@detail.TeamLeader%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="skill-bar-item">
                                <span>development</span>
                                <div class="progress">
                                    <div data-wow-delay="1.2s" data-wow-duration="1.5s" style="width: 85%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-progress="50%" class="progress-bar wow fadeInLeft">
                                        <span class="text-top">@detail.Development%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="skill-bar-item">
                                <span>design</span>
                                <div class="progress">
                                    <div data-wow-delay="1.2s" data-wow-duration="1.5s" style="width: 95%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-progress="50%" class="progress-bar wow fadeInLeft">
                                        <span class="text-top">@detail.Design%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="skill-bar-item">
                                <span>innovation</span>
                                <div class="progress">
                                    <div data-wow-delay="1.2s" data-wow-duration="1.5s" style="width: 85%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-progress="50%" class="progress-bar wow fadeInLeft">
                                        <span class="text-top">@detail.Innovation%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="skill-bar-item">
                                <span>communication</span>
                                <div class="progress">
                                    <div data-wow-delay="1.2s" data-wow-duration="1.5s" style="width: 95%; visibility: visible; animation-duration: 1.5s; animation-delay: 1.2s; animation-name: fadeInLeft;" data-progress="50%" class="progress-bar wow fadeInLeft">
                                        <span class="text-top">@detail.Communication%</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Teacher End -->
<!-- Subscribe Start -->
<div class="subscribe-area pt-60 pb-70">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="subscribe-content section-title text-center">
                    <h2>subscribe our newsletter</h2>
                    <p>I must explain to you how all this mistaken idea </p>
                </div>
                <div class="newsletter-form mc_embed_signup">
                    <form action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                        <div id="mc_embed_signup_scroll" class="mc-form">
                            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Enter your e-mail address" required>
                            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                            <div class="mc-news" aria-hidden="true"><input type="text" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef" tabindex="-1" value=""></div>
                            <button id="mc-embedded-subscribe" class="default-btn" type="submit" name="subscribe"><span>subscribe</span></button>
                        </div>
                    </form>
                    <!-- mailchimp-alerts Start -->
                    <div class="mailchimp-alerts">
                        <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                        <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                        <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                    </div>
                    <!-- mailchimp-alerts end -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Subscribe End -->

Eduhome/Eduhome/Views/Teacher/Index.cshtml
@{
    ViewData["Title"] = "Index";
    List<Teacher> teachers = Model;
}

<!-- Banner Area Start -->
<div class="banner-area-wrapper">
    <div class="banner-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="banner-content-wrapper">
                        <div class="banner-content">
                            <h2>our teachers</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Area End -->
<!-- Teacher Start -->
<div class="teacher-area pt-150 pb-105">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="course-title">
                    <h3>search teachers</h3>
                </div>
                <div class="course-form">
                    <form asp-controller="Teacher" asp-action="Search" id="course-search">
                        <input type="search" placeholder="Search..." name="search" id="teacher-input" />
                        <button type="submit">search</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            @foreach (Teacher t in teachers)
            {
                <div class="col-md-3 col-sm-4 col-xs-12">
                    <div class="single-teacher mb-45">
                        <div class="single-teacher-img">
                            <a asp-controller="Teacher" asp-action="Details" asp-route-id="@t.Id">
                                <img src="~/front/img/teacher/@t.Image" alt="teacher">
                            </a>
                        </div>
                        <div class="single-teacher-content text-center">
                            <h2><a asp-controller="Teacher" asp-action="Details" asp-route-id="@t.Id">@t.Name</a></h2>
                            <h4>@t.Position</h4>
                            <ul>
                                <li><a href="https://www.facebook.com/devitems/?ref=bookmarks"><i class="zmdi zmdi-facebook"></i></a></li>
                                <li><a href="https://www.pinterest.com/devitemsllc/"><i class="zmdi zmdi-pinterest"></i></a></li>
                                <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                                <li><a href="https://twitter.com/devitemsllc"><i class="zmdi zmdi-twitter"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            }


        </div>
    </div>
</div>
<!-- Teacher End -->
<!-- Subscribe Start -->
<div class="subscribe-area pt-60 pb-70">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="subscribe-content section-title text-center">
                    <h2>subscribe our newsletter</h2>
                    <p>I must explain to you how all this mistaken idea </p>
                </div>
                <div class="newsletter-form mc_embed_signup">
                    <form action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                        <div id="mc_embed_signup_scroll" class="mc-form">
                            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Enter your e-mail address" required>
                            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                            <div class="mc-news" aria-hidden="true"><input type="text" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef" tabindex="-1" value=""></div>
                            <button id="mc-embedded-subscribe" class="default-btn" type="submit" name="subscribe"><span>subscribe</span></button>
                        </div>
                    </form>
                    <!-- mailchimp-alerts Start -->
                    <div class="mailchimp-alerts">
                        <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                        <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                        <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                    </div>
                    <!-- mailchimp-alerts end -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Subscribe End -->

Eduhome/Eduhome/Views/Teacher/Search.cshtml
@{
    ViewData["Title"] = "Search Teacher";
    List<Teacher> teachers = Model;
}

<!-- Banner Area Start -->
<div class="banner-area-wrapper">
    <div class="banner-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="banner-content-wrapper">
                        <div class="banner-content">
                            <h2>our teachers</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Area End -->
<!-- Teacher Start -->
<div class="teacher-area pt-150 pb-105">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="teacher-title">
                    <h3>search teachers</h3>
                </div>
                <div class="course-form">
                    <form asp-controller="Teacher" asp-action="Search" id="teacher-search">
                        <input type="search" placeholder="Search..." name="search" id="teacher-input" />
                        <button type="submit">search</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            @foreach (Teacher t in teachers)
            {
                <div class="col-md-3 col-sm-4 col-xs-12">
                    <div class="single-teacher mb-45">
                        <div class="single-teacher-img">
                            <a asp-controller="Teacher" asp-action="Details" asp-route-id="@t.Id">
                                <img src="~/front/img/teacher/@t.Image" alt="teacher">
                            </a>
                        </div>
                        <div class="single-teacher-content text-center">
                            <h2><a asp-controller="Teacher" asp-action="Details" asp-route-id="@t.Id">@t.Name</a></h2>
                            <h4>@t.Position</h4>
                            <ul>
                                <li><a href="https://www.facebook.com/devitems/?ref=bookmarks"><i class="zmdi zmdi-facebook"></i></a></li>
                                <li><a href="https://www.pinterest.com/devitemsllc/"><i class="zmdi zmdi-pinterest"></i></a></li>
                                <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                                <li><a href="https://twitter.com/devitemsllc"><i class="zmdi zmdi-twitter"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            }


        </div>
    </div>
</div>
<!-- Teacher End -->
<!-- Subscribe Start -->
<div class="subscribe-area pt-60 pb-70">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="subscribe-content section-title text-center">
                    <h2>subscribe our newsletter</h2>
                    <p>I must explain to you how all this mistaken idea </p>
                </div>
                <div class="newsletter-form mc_embed_signup">
                    <form action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                        <div id="mc_embed_signup_scroll" class="mc-form">
                            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Enter your e-mail address" required>
                            <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                            <div class="mc-news" aria-hidden="true"><input type="text" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef" tabindex="-1" value=""></div>
                            <button id="mc-embedded-subscribe" class="default-btn" type="submit" name="subscribe"><span>subscribe</span></button>
                        </div>
                    </form>
                    <!-- mailchimp-alerts Start -->
                    <div class="mailchimp-alerts">
                        <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                        <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                        <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                    </div>
                    <!-- mailchimp-alerts end -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Subscribe End -->