Eduhome/Eduhome/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eduhome.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Eduhome/Eduhome/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eduhome.Controllers
{
    public class BlogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Eduhome/Eduhome/Controllers/CourseController.cs
using Eduhome.DAL;
using Eduhome.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eduhome.Controllers
{
    public class CourseController : Controller
    {
        private readonly AppDbContext _db;
        public CourseController(AppDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            List<Caption> courses =await _db.CourseCaptions.ToListAsync();
            
            return View(courses);
        }
        public IActionResult Details(int? id)
        {
            if (id == null) return RedirectToAction("Index");
            CourseDetails detail = _db.CourseDetails.Include(det=>det.Caption)
                .FirstOrDefault(det=>det.CaptionId==id);
            if (detail == null) return RedirectToAction("Index");

            return View(detail);
        }
        public async Task<IActionResult> Search(string search)
        {
            List<Caption> courses = await _db.CourseCaptions.Where(c=>c.Title.ToLower().Trim().Contains(search.ToLower().Trim())).ToListAsync();
            
            return View(courses);
        }
    }
}

Eduhome/Eduhome/Controllers/EventController.cs
using Eduhome.DAL;
using Eduhome.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Eduhome.Controllers
{
    public class EventController : Controller
    {
        private readonly AppDbContext _db;
        public EventController(AppDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            List<Event> events = await _db.Event.ToListAsync();

            return View(events);
        }
        public IActionResult Details(int id)
        {

            EventDetails detail = _db.EventDetails.Include(det => det.Event).Include(x=>x.EventSpeakers).ThenInclude(x=>x.Speaker)
                .FirstOrDefault(det => det.EventId == id);


            return View(detail);
        }
        public async Task<IActionResult> Search(string search)
        {
            List<Event> events = await _db.Event.Where(c => c.Title.ToLower().Trim().Contains(search.ToLower().Trim())).ToListAsync();

            return View(events);
        }
    }
}

Eduhome/Eduhome/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<!-- Mirrored from demo.devitems.com/eduhome/index-2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 21 Jun 2020 19:37:50 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Eduhome - Educational HTML Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!-- Place favicon.ico in the root directory -->

    <link rel="stylesheet" href="~/front/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/front/css/animate.css">
    <link rel="stylesheet" href="~/front/css/meanmenu.css">
    <link rel="stylesheet" href="~/front/css/magnific-popup.css">
    <link rel="stylesheet" href="~/front/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/front/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/front/css/et-line-icon.css">
    <link rel="stylesheet" href="~/front/css/reset.css">
    <link rel="stylesheet" href="~/front/css/ionicons.min.css">
    <link rel="stylesheet" href="~/front/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="~/front/css/style.css">
    <link rel="stylesheet" href="~/front/css/responsive.css">
    <script src="~/front/js/vendor/modernizr-2.8.3.min.js"></script>
</head>
<body>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Header Area Start -->
    <header class="top">
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-8 col-xs-12">
                        <div class="header-top-left">
                            <p>HAVE ANY QUESTION ?  +880 5698  598  6587</p>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-12">
                        <div class="header-top-right text-right">
                            <ul>
                                <li><a href="login.html">login</a></li>
                                <li><a href="signup.html">signup</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-area two header-sticky">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-3 col-xs-6">
                        <div class="logo">
                            <a asp-controller="Home" asp-action="Index"><img src="~/front/img/logo/logo2.png" alt="eduhome" /></a>
                        </div>
                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-6">
                        <div class="content-wrapper text-right">
                            <!-- Main Menu Start -->
                            <div class="main-menu">
                                <nav>
                                    <ul>
                                        <li>
                                            <a asp-controller="Home" asp-action="Index">Home</a>
                                        </li>
                                        <li><a  asp-controller="About" asp-action="Index">About</a></li>
                                        <li>
                                            <a  asp-controller="Course" asp-action="Index">courses</a>
                                        </li>
                                        <li>
                                            <a  asp-controller="Event" asp-action="Index">event</a>  
                                        </li>
                                        <li class="hidden-sm">
                                            <a  asp-controller="Teacher" asp-action="Index">teacher</a>
                                        </li>
                                        <li>
                                            <a  asp-controller="Blog" asp-action="Index">blog</a>
                                        </li>
                                        <li><a  asp-controller="Contact" asp-action="Index">Contact</a></li>
                                    </ul>
                                </nav>
                            </div>
                            <!--Search Form Start-->
                            <div class="search-btn">
                                <ul data-toggle="dropdown" class="header-search search-toggle">
                                    <li class="search-menu">
                                        <i class="fa fa-search"></i>
                                    </li>
                                </ul>
                                <div class="search">
                                    <div class="search-form">
                                        <form id="search-form" action="#">
                                            <input type="search" placeholder="Search here..." name="search" />
                                            <button type="submit">
                                                <span><i class="fa fa-search"></i></span>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <!--End of Search Form-->
                            <!-- Main Menu End -->
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="mobile-menu hidden-lg hidden-md hidden-sm"></div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    @RenderBody()

    <!-- Footer Start -->
    <footer class="footer-area">
        <div class="main-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="single-widget pr-60">
                            <div class="footer-logo pb-25">
                                <a asp-controller="Home" asp-action="Index"><img src="~/front/img/logo/footer-logo.png" alt="eduhome"></a>
                            </div>
                            <p>I must explain to you how all this mistaken idea of denoung pleure and praising pain was born and give you a coete account of the system. </p>
                            <div class="footer-social">
                                <ul>
                                    <li><a href="#"><i class="zmdi zmdi-facebook"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-pinterest"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-twitter"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="single-widget">
                            <h3>information</h3>
                            <ul>
                                <li><a href="#">addmission</a></li>
                                <li><a href="#">Academic Calender</a></li>
                                <li><a href="event.html">Event List</a></li>
                                <li><a href="#">Hostel &amp; Dinning</a></li>
                                <li><a href="#">TimeTable</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                        <div class="single-widget">
                            <h3>useful links</h3>
                            <ul>
                                <li><a href="course.html">our courses</a></li>
                                <li><a href="about.html">about us</a></li>
                                <li><a href="teacher.html">teachers &amp; faculty</a></li>
                                <li><a href="#">teams &amp; conditions</a></li>
                                <li><a href="event.html">our events</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="single-widget">
                            <h3>get in touch</h3>
                            <p>Your address goes here, Street<br>City, Roadno 785 New York</p>
                            <p>+880  548  986  898  87<br>+880  659  785  658  98</p>
                            <p>info@eduhome.com<br>www.eduhome.com</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom text-center">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <p>Copyright © <a href="#" target="_blank">HasTech</a> 2017. All Right Reserved By Hastech.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer End -->

    <script src="~/front/js/vendor/jquery-1.12.0.min.js"></script>
    <script src="~/front/js/bootstrap.min.js"></script>
    <script src="~/front/js/jquery.meanmenu.js"></script>
    <script src="~/front/js/jquery.magnific-popup.js"></script>
    <script src="~/front/js/ajax-mail.js"></script>
    <script src="~/front/js/owl.carousel.min.js"></script>
    <script src="~/front/js/jquery.mb.YTPlayer.js"></script>
    <script src="~/front/js/jquery.nicescroll.min.js"></script>
    <script src="~/front/js/plugins.js"></script>
    <script src="~/front/js/main.js"></script>
</body>

<!-- Mirrored from demo.devitems.com/eduhome/index-2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 21 Jun 2020 19:41:25 GMT -->
</html>